#cloud-config
hostname: ${VM_NAME}
fqdn: ${VM_NAME}
disable_root: false
network:
  config: disabled
users:
  - name: ${USERNAME}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWORD}
    ssh_import_id:
      - gh:${GITHUB_USER}
  - name: ${VM_ADMIN}
    gecos: system acct
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWORD}
    ssh_authorized_keys:
      - ${VM_KEY}
write_files:
- path: /etc/netplan/99-my-new-config.yaml
  permissions: '0644'
  content: |
    network:
      ethernets:
        ${INTERFACE}:
          dhcp4: no
          dhcp6: no
          addresses: [${STATIC_IP_ADDRESS}/24]
          routes:
            - to: default
              via: ${GATEWAY_IP}
          mtu: 1500
          nameservers:
            addresses: [${DNS_SERVER_IP}]
      renderer: networkd
      version: 2
package_update: ${UPDATE}
package_upgrade: ${UPGRADE}
runcmd:
  - sudo netplan --debug generate
  - sudo netplan --debug apply
  - sed -i -e '/^Port/s/^.*$/Port 22/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
